#!/usr/bin/env ruby

require_relative "./potter"

if ARGV.length != 5
  puts "il faut mettre la quantité de chaque tome acheté"
  puts "ex: ./main 0 0 0 0 0"
  puts "ex: ./main 1 3 0 0 2"
  puts "essai encore"
  exit(1)
end


prix_a_payer = potter(ARGV)

puts "prix à payer : #{prix_a_payer} euros"